Azure/iotedgedev

- iotedgedev/azurecli.py
- tests/test_azurecli.py
- When searching for the subscription id, lowercase the search token
- When multiple subscriptions match, do not assume the first was desired
> Lowercase the search token for subscription ids, and handle ambiguous or empty results

- .env.tmp
- iotedgedev/azurecli.py
- iotedgedev/dockercls.py
- iotedgedev/envvars.py
- iotedgedev/modules.py
- iotedgedev/template/.env.tmp
- tests/test_envvars.py
The benefit of adding the underscore:
1. Clarity: `CONTAINER_REGISTRY_SERVER_PRODUCTION` vs. `CONTAINER_REGISTRY_SERVERPRODUCTION`
2. Compatibility with the .env file generated by the VS Code extension: https://github.com/Microsoft/vscode-azure-iot-edge/blob/master/src/edge/edgeManager.ts#L501-L502
Also fix #265
> Add an underscore after additional registry environment key prefixes

- iotedgedev/azurecli.py
- tests/test_simulator.py
This pull request addresses [issue 228](https://github.com/Azure/iotedgedev/issues/288).
The changes essentially remove any reliance on Popen.communicate timeout (Python 3.3+ only) and uses a thread Timer approach for elements that require a 'timeout'. In addition stdout + stderr processing is explicitly handled in the parent process to allow straightforward interrupt handling from parent -> child processes. This pattern is implemented for monitor_events.
Also a test assertion in test_simulator is commented out as the particular output is not triggering and may be out of place.
> Reworked monitor events integration

- iotedgedev/dockercls.py
- iotedgedev/modules.py
Fixes #327 and fixes #287 
Now build output shows in real time with more detailed information:
When something wrong happens:
> Improve docker build output

- iotedgedev/dockercls.py
- iotedgedev/output.py
For some tools such as Maven, output are piped on a character basis instead of line.
Known issue: ANSI color codes are not correctly shown as ANSI color control sequences and codes are piped separately from docker API output:
> Handle new line in docker output correctly

- iotedgedev/dockercls.py
Docker API streams output in JSON format. For `docker build`, we care about the `stream` property in the JSON, while for `docker push`, we care about the `status` property. The `stream` property comes with newlines, while the `status` property not. See Docker CLI's reference handling of [`stream`](https://github.com/docker/cli/blob/master/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go#L237-L238) and [`status`](https://github.com/docker/cli/blob/master/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go#L233-L234)
Current output of `iotedgedev build`:
`iotedgedev push --no-build`:
> Append new lines to docker push status output

- .vsts-ci.yml
Hosted Linux Preview pool is being deprecated on December 1, 2018.
> Migrate AZDO pool to Hosted Ubuntu 1604

- README.md
We are migrating the Azure DevOps to our mseng eng account with allows more parallelism and faster build.
> Update Azure DevOps badge to point to mseng

- docker/runtime/Dockerfile
- docker/runtime/rund.sh
host.docker.internal is not available in docker for linux, use the actual ip address when host.docker.internal is unavailable
> Fix host.docker.internal not available in linux docker issue

- iotedgedev/azurecli.py
There was a key error here, and now it is using the full-blown "connectionString" as the key.
It is related to this issue: https://github.com/Azure/iotedgedev/issues/387
If 'cs' is being used by older versions of the Azure CLI, for example, there could be room here to check to see if the key exists before trying to grab it.
> Fixed issue with 'cs' keyerror

- iotedgedev/module.py
- iotedgedev/modules.py
Fix #396 
1. Allow non module project.
2. Remove language property which is not used in IoT Edge development now. Some customers removed this property in module.json, so reading this property may cause errors.
3. Fix unicode error in python2 due to recent commentjson update
> allow non module project 

- CHANGELOG.md
- iotedgedev/__init__.py
- setup.cfg
- setup.py
The latest [lark-parser](https://pypi.org/project/lark-parser/) release breaks commentjson. Revert the version of commentjson to old version which doesn't use lark-parser.
> do not use lark-parser enabled commentjson and bump version to 2.0.2

- CHANGELOG.md
- iotedgedev/__init__.py
- setup.cfg
- setup.py
Failed to install more-itertools on Azure Pipelines when installing iotedgedev.
> Fix installation error on Azure Pipelines caused by more-itertools

- CHANGELOG.md
- iotedgedev/__init__.py
- iotedgedev/deploymentmanifest.py
- setup.cfg
- setup.py
- tests/assets/deployment.manifest_invalid_createoptions.json
- tests/assets/deployment.manifest_invalid_schema.json
- tests/test_iotedgedev.py
Fix genconfig does not fail when schema validation failed #424 
AB#1696447
> Fix genconfig does not fail when schema validation failed

- CHANGELOG.md
- docker/tool/linux/Dockerfile.base
- iotedgedev/__init__.py
- setup.cfg
- setup.py
The latest azure cli core version only works on python3, revert to previous version to fix errors on python2
> Fix error caused by latest azure cli core version

- .travis.yml
- docker/tool/linux/Dockerfile.base
Ubuntu 19.04 has reached end of life. Use LTS version of ubuntu to avoid command failures on non-LTS distribution
> Use ubuntu 18.04 LTS as base image

- CONTRIBUTING.md
- docker/tool/linux/Dockerfile.base
- docker/tool/windows/Dockerfile.base
- iotedgedev/cli.py
- iotedgedev/constants.py
- setup.py
1. Specify bcrypt <= 3.1.7 to fix errors on Azure Pipelines linux agent
2. Install azure-iot instead of the old azure-cli-iot-ext extension
> Fix bcrypt error

- .vscode/launch.json
- CHANGELOG.md
- iotedgedev/__init__.py
- iotedgedev/telemetryconfig.py
- setup.cfg
- setup.py
closes #338 
Replaced readfp with read_file as readfp is being deprecated. Ran unit tests and regression tests with no new issues detected.
> Load config file using read_file as readfp is being deprecated

- iotedgedev/azurecli.py
`az iot hub list` returns the parameter `resourcegroup` in lowercase.
As https://github.com/Azure/azure-cli/pull/8950/files suggests, this is true since at least 3 Apr 2019.
> Fix parsing the output of `az iot hub list`

- vsts_ci/win32/continuous-build-win32.yml
This is a work around an az cli issue. All iotedgedev pipelines pass with this fix.
> Update setuptools so az cli can be used within the Windows devops pipeline

- iotedgedev/__init__.py
- requirements.txt
- setup.cfg
- setup.py
- tests/__init__.py
version 3.1.1
- baseline az-cli dependency to 2.25.0 or greater (azure-cli-core)
- remove out of date and unused azure-cli-cloud and other dependencies
> baseline az-cli version

- tests/assets/test_solution_shared_lib/modules/sample_module/Dockerfile.amd64
- tests/assets/test_solution_shared_lib/modules/sample_module/Dockerfile.amd64.debug
- tests/assets/test_solution_shared_lib/modules/sample_module/Dockerfile.windows-amd64
- tests/assets/test_solution_shared_lib/sample_module_2/Dockerfile.amd64
- tests/assets/test_solution_shared_lib/sample_module_2/Dockerfile.amd64.debug
- tests/assets/test_solution_shared_lib/sample_module_2/Dockerfile.windows-amd64
This failure is blocking CICD for iotedgedev
https://devblogs.microsoft.com/dotnet/net-core-2-1-container-images-will-be-deleted-from-docker-hub/
> Update dotnet docker image refs from dockerhub to mcr

- iotedgedev/cli.py
Some commands can be called in two different ways (for instance,
`iotedgedev init` and `iotedgev solution init`). Eventually, this
duplication should be removed to simplify the tool. This is a breaking
change, though; so before implementing it in the next major release, we
should add a deprecation notice in such commands. This deprecation
notice should be added to the help message and printed when the command
is run. This can be done by setting `deprecated=True` in the
`click.Command()` decorator (see
[documentation](https://click.palletsprojects.com/en/8.1.x/api/#click.Command)).
Note that the reason for this duplication is that the commands are added
to two `click` groups (`main` and `solution`). …
> Deprecate duplicate commands

- iotedgedev/azurecli.py
Fixes #534
Creating a F1 IoT Hu requires setting the partition count to 2. The default from the CLI is 4, so in case F1 is requested the partition count is added to the command.
> fix: allow default IoT Hub SKUs (F1)

- CHANGELOG.md
- iotedgedev/__init__.py
- iotedgedev/dotnet.py
- setup.cfg
- setup.py
- tests/__init__.py
- tests/test_iotedgedev_solution.py
- tests/test_iotedgedev_solution_build.py
> Lock .NET template version to 3.2.0
