Azure/iotedgedev

iotedgedev/cli.py

#21  - a small chance collision implementation

pseudo unique iot hub name generation

---

README.md
requirements.txt
requirements_nodeps.txt
setup.py

Lightweight Az CLI via pip install method.

---

setup.py

Improved post install hook for py 27.

---

iotedgedev/cli.py
iotedgedev/solution.py
iotedgedev/utility.py
tests/test_iotedgedev.py

check if dir is empty on init and prompt accordingly

---

CODE_OF_CONDUCT.md
LICENSE

Copied files from opensource.microsoft.com. Close #136

Update license file, update code of conduct

---

iotedgedev/azurecli.py
iotedgedev/connectionstring.py
iotedgedev/edge.py
tests/test_connectionstring.py

AZ IOT HUB apply-configuration needs hubname

---

README.md
iotedgedev/dotnet.py
iotedgedev/modules.py
iotedgedev/utility.py

Resolve Jon's comment on the [commit to add "add module" command](https://github.com/Azure/iotedgedev/commit/4ff937cb2a71d4405394121ebfecb7b3e8070d69).

Resolve review comment

---

iotedgedev/deploymentmanifest.py
iotedgedev/template/deployment.template.json
iotedgedev/utility.py
setup.cfg
tests/assets/deployment.template_1.json
tests/assets/deployment.template_2.json
tests/assets/deployment.template_3.json
tests/conftest.py
tests/test_deploymentmanifest.py
tests/test_iotedgedev.py
tests/test_utility.py
tests/utility.py

This PR implements https://github.com/Azure/iotedgedev/issues/212 and fixes https://github.com/Azure/iotedgedev/issues/213.

Support new schema of deployment.json with backward compatibility

---

iotedgedev/azurecli.py
iotedgedev/cli.py
iotedgedev/dockercls.py
iotedgedev/envvars.py
iotedgedev/modules.py
iotedgedev/organizedgroup.py
iotedgedev/solution.py

Discussion issue: https://github.com/Azure/iotedgedev/issues/219
All feedbacks are welcome. :)

Redesign CLI UX

---

iotedgedev/dockercls.py
iotedgedev/modules.py

Process Docker API response (fix #198)

---

iotedgedev/cli.py
iotedgedev/envvars.py
tests/test_envvars.py
tests/test_iotedgedev.py
tests/test_simulator.py

Rename `iotedgedev create` to `iotedgedev new`

---

iotedgedev/cli.py
iotedgedev/dockercls.py
iotedgedev/utility.py

Fix issues with iotedgedev log command

---

iotedgedev/cli.py
iotedgedev/envvars.py
iotedgedev/solution.py
iotedgedev/utility.py

Close https://github.com/Azure/iotedgedev/issues/286 and close https://github.com/Azure/iotedgedev/issues/283
Also, fail fast if the cwd is empty when solution init (related:#191).

Promote init and allow customization

---

iotedgedev/envvars.py

Fix https://github.com/Azure/iotedgedev/issues/282

Fix solution init error

---

requirements.txt
setup.py

Include pypiwin32 in requirements

---

iotedgedev/decorators.py
tests/test_decorators.py

Add tests for hash256_result, refine tests for suppress_all_exceptions

---

docker/runtime/readme.md
docker/tool/linux/Dockerfile
docker/tool/linux/Dockerfile.base
docker/tool/windows/Dockerfile.base
docker/tool/windows/run.ps1

Fix #312. 
Also fix #242, fix #244 and add Git which is depended by cookiecutter.

Fix Yeoman's permission issue in Linux container

---

build.sh
docker/tool/build-docker.sh
docker/tool/linux/Dockerfile.base
iotedgedev/__init__.py

Also fixing the dockerfile to have update and install on same line. Was getting error on docker build without that.

Move AIkey set to build.sh.

---

iotedgedev/__init__.py
iotedgedev/azurecli.py
iotedgedev/cli.py

Retry subscription prompt when multiple search results found

---

.vscode/settings.json
iotedgedev/cli.py
iotedgedev/deploymentmanifest.py
iotedgedev/module.py
iotedgedev/modules.py
iotedgedev/template/launch_c.json
tests/assets/launch.json
tests/test_iotedgedev.py

Support adding C modules

---

iotedgedev/cli.py
iotedgedev/decorators.py
iotedgedev/modules.py
iotedgedev/solution.py
iotedgedev/template/launch_java.json
tests/assets/launch.json
tests/test_iotedgedev.py

Support adding Java modules

---

iotedgedev/azurecli.py
iotedgedev/connectionstring.py
iotedgedev/decorators.py
iotedgedev/edge.py
iotedgedev/iothub.py
iotedgedev/telemetry.py
iotedgedev/utility.py
tests/test_connectionstring.py
tests/test_iotedgedev.py
tests/test_simulator.py
tests/test_utility.py

This is a BI requirement.
@chyuanmsft, please help take a look.

Collect IoT Hub hostname hash and suffix when deploying

---

CONTRIBUTING.md

Add dependency installation steps to CONTRIBUTING.md

---

.vscode/launch.json
iotedgedev/dockercls.py

Fix issue starting local registry with custom ports

---

iotedgedev/dockercls.py
iotedgedev/envvars.py

`docker.from_env` will simply pick up all the necessary environment variables to connect to a Docker daemon.

Fix issue connecting to Docker daemon with tlsverify enabled

---

iotedgedev/cli.py
iotedgedev/simulator.py
requirements.txt
setup.py
tests/test_simulator.py

1. Support iotedgehubdev new setup parameter `-i`
2. Update applicationinsights dependency to avoid breaking installation (#383)
3. Update azure-cli-core dependency to avoid breaking deploy function (error loading command module cloud)

Support iotedgehubdev new setup parameter

---

requirements.txt
setup.py

'click' package should be lower case: https://pypi.org/project/click/

Fix case sensitivity for 'click' package

---

.env.tmp
iotedgedev/template/.env.tmp

Resolves #398 
#395 - User had issue figuring out how to use Docker Hub.  This should clear things up.

Add better Docker Hub instructions

---

iotedgedev/dockercls.py
tests/test_iotedgedev.py
tests/utility.py

Add progress info when downloading/pushing images
Fix #397

Add progress info

---

iotedgedev/modules.py
setup.py
tests/assets/deployment.template.non_str_placeholder.json
tests/test_iotedgedev.py

1. Do not validate deployment template schema
2. Do not specify version of msrestazure since it conflicts with latest azure-cli-core package and related issue is resolved
3. Update version of pyyaml to avoid version conflict with iotedgehubdev

fix #414 and dependency error

---

docker/tool/linux/Dockerfile.base

Upgrade container base image to 19.04 to fix vulnerable USN-4209-1

Upgrade container base image to fix vulnerability issue

---

README.md

IoT Edge simulator is able to run python and c module

Update latest simulator language support info

---

CHANGELOG.md
iotedgedev/__init__.py
setup.cfg
setup.py

bump version to 2.1.5

---

.vscode/settings.json
requirements_dev.txt
vsts_ci/linux/continuous-build-linux.yml
vsts_ci/win32/continuous-build-win32.yml

* Remove cryptography package as setuptools already includes this package
* Let system determine value of JAVA_HOME env var
* Add local registry script to Windows .yaml

CI CD Pipeline Fix: Remove conflicting cryptography package, run local container registry

---

.vscode/settings.json
CHANGELOG.md
iotedgedev/__init__.py
requirements_dev.txt
setup.cfg
setup.py
vsts_ci/linux/continuous-build-linux.yml
vsts_ci/win32/continuous-build-win32.yml

* Fix dependency conflicts in testing 
* Update IoT Hub endpoint for testing 
* Enable local CR on Windows agent

Fix CI/CD pipeline execution | Add local CR for Windows

---

requirements.txt
setup.py

- set minimum version to 'iotedgehubdev >= 0.14.3'

update iotedgehubdev minimum version

---

docker/tool/linux/Dockerfile.base

- update node version
- remove old node dependency

Unblock build_docker.sh and Update Dockerfile.base

---

docker/tool/push-docker.sh

MCR push process is already described at "MCR push process" OneNote. This change will make sure to not push to DockerHub but instead to MCR.

Push iotedgedev container to MCR

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CONTRIBUTING.md

Adding the initial devcontainer mentioned in issue #488
If this looks good, I can also add onto the contribution docs to refer to the devcontainer.
Let me know if I'm missing anything or you'd like something else in it.

Add devcontainer

---

iotedgedev/__init__.py
iotedgedev/azurecli.py
pull_request_template.md
setup.cfg
setup.py
tests/__init__.py

- updated AZ CLI show connection string commands
- added PR checklist template

AZ CLI Connection Strings Update

---

iotedgedev/__init__.py
setup.cfg
setup.py
tests/__init__.py

3.1.2 update release version

---

iotedgedev/__init__.py
setup.cfg
setup.py
tests/__init__.py

3.2.0 update tags

---

.github/workflows/wiki.yml

- Fix pipeline failing due to a non zero error code being outputted incorrectly
- Add additional logging
Previously failing pipeline:
Failing pipeline: https://github.com/Azure/iotedgedev/actions/runs/1193151397
Pipelines succeeding with the new changes:
Successful run with changes to the wiki: https://github.com/Azure/iotedgedev/actions/runs/1194319268
Successful run with **no** changes to the wiki: https://github.com/Azure/iotedgedev/runs/3495439352?check_suite_focus=true

Fix issue with the pipeline failing despite successful completion 

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
docs/Command-List.md
docs/Usage.md
iotedgedev/cli.py

As discussed, adding documentation for how to use the new iothub deploy command. Let me know if there's anything I've missed.

Update documentation with iothub deploy command

---

vsts_ci/.vsts-ci.yml

Add PR trigger to Azure Devops pipeline

---

tests/test_cli.py
tests/utility.py

WARNING: Do not merge this branch until #500  has been merged and I've updated this to merge to master

Add cli structure test

---

docs/Command-List.md

Update docs with device tagging command

---

docs/Usage.md
iotedgedev/cli.py

Adding changes in addition to the changes found in #506
(due to not having the ability to update the branch of #506)

Update docs with device tagging command Vol. 2

---

iotedgedev/__init__.py
iotedgedev/connectionstring.py
iotedgedev/envvars.py
setup.cfg
setup.py
tests/__init__.py
tests/test_connectionstring.py

- in response to issue https://github.com/Azure/iotedgedev/issues/482

Handle non SAS connection strings

---

azure-pipelines.yml

Update release pipeline to generate manifest and target 1ES agent pools.

Generate SBOM + target 1ES pool

---

README.md
docs/_Sidebar.md
vsts_ci/.vsts-ci.yml

Update pointers to main branch

Update pointers to main branch

---

README.md
docs/_Sidebar.md
vsts_ci/.vsts-ci.yml

Cherry-pick: Rename (#519)

---

CHANGELOG.md
iotedgedev/__init__.py
requirements.txt
setup.cfg
setup.py
tests/__init__.py

Lock simulator version

---

.github/pull_request_template.md
pull_request_template.md

Update PR template to include:
-  a description section
- add test coverage and documents update to checklist
- issue number section

Update PR template

---

CONTRIBUTING.md

Fixes #577
Small fix to the CONTRIBUTING file to clarify the order and point out that the fork must be used. Also added a hint towards Codespaces.

docs: change the order of steps in Contributing for clarity

---

CHANGELOG.md
iotedgedev/__init__.py
setup.cfg
setup.py
tests/__init__.py

Update change log and increment version to prepare for the next release.

Update change log and increment version

---

.github/workflows/wiki.yml

Fix wiki pipeline

---

CHANGELOG.md
iotedgedev/__init__.py
requirements.txt
setup.cfg
setup.py
tests/__init__.py

Fixes #
Update simulator's version

Update simulator's version

---

iotedgedev/azurecli.py

Fixes #597 
For some calls to `az cli`, the results get parsed by `json.loads` method. For these calls, we need to ensure the output is set correctly, in case the user has different defaults (these defaults can be changed with `az configure`).

fix: force json output for results that get parsed

---

azure-pipelines.yml
docker/tool/push-docker.sh
tests/test_iotedgedev_simulator.py
tests/test_iotedgedev_solution.py
tests/test_iotedgedev_solution_build.py
vsts_ci/.vsts-ci.yml

Update iotedgedev containers ACR reference
